-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 09:49:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema houses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema houses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `houses` DEFAULT CHARACTER SET utf8 ;
USE `houses` ;

-- -----------------------------------------------------
-- Table `houses`.`accommodations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses`.`accommodations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `accuracy` FLOAT UNSIGNED NOT NULL,
  `communication` FLOAT UNSIGNED NOT NULL,
  `cleanliness` FLOAT UNSIGNED NOT NULL,
  `checkIn` FLOAT UNSIGNED NOT NULL,
  `value` FLOAT UNSIGNED NOT NULL,
  `location` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `houses`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houses`.`reviews` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `accommodationId` INT(10) UNSIGNED NOT NULL,
  `userName` VARCHAR(32) NOT NULL,
  `userPicture` VARCHAR(255) NOT NULL,
  `userPageLink` VARCHAR(255) NOT NULL,
  `date` VARCHAR(255) NOT NULL,
  `reviewText` BLOB NOT NULL,
  `accuracy` FLOAT UNSIGNED NOT NULL,
  `communication` FLOAT UNSIGNED NOT NULL,
  `cleanliness` FLOAT UNSIGNED NOT NULL,
  `checkIn` FLOAT UNSIGNED NOT NULL,
  `value` FLOAT UNSIGNED NOT NULL,
  `location` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accommodationID_idx` (`accommodationId` ASC) VISIBLE,
  CONSTRAINT `fk_accommodationID`
    FOREIGN KEY (`accommodationId`)
    REFERENCES `houses`.`accommodations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
